In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("movies.csv")
df.head(3)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English

In [9]:
df.shape

(37, 10)

In [11]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='object')

In [13]:
df.industry.unique()

array(['Bollywood', 'Hollywood'], dtype=object)

In [19]:
df['language'].unique()

array(['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu'], dtype=object)

In [21]:
df.industry.value_counts()

industry
Hollywood    20
Bollywood    17
Name: count, dtype: int64

In [23]:
# how many movies are there for each of these languages

df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [27]:
df["age"]=df['release_year'].apply(lambda x: 2026-x)

In [29]:
df.head(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9